name: task_master
description: TaskMaster is a simple and intuitive task management application designed to help you organize your daily life effectively, allowing you to create, organize, and track tasks with ease

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  gap: ^3.0.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/svg/
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-BoldItalic.ttf
        - asset: assets/fonts/DMSans-Italic.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-MediumItalic.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
